"""
Schema discovery tool.
Queries every Notion database's data source and outputs property names, types, and options.
Run this first to map your Notion setup before building queries.

Usage: python tools/discover_schema.py
Output: workflows/notion_database_map.md
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from tools.notion_client_wrapper import get_client, get_db_id, retrieve_data_source_schema
from dotenv import load_dotenv

load_dotenv()

# All database env var suffixes
DB_NAMES = [
    "TASKS", "PROJECTS", "WORK_SESSIONS", "NOTES", "TAGS",
    "GOALS", "MILESTONES", "PEOPLE",
    "BOOKS", "READING_LOG", "BOOK_GENRES",
    "RECIPES", "RECIPE_TAGS", "MEAL_PLANNER",
    "KITCHEN_INVENTORY", "PANTRY_PROCESSOR",
    "MOVIES", "MOVIE_LOG", "MOVIE_GENRES",
]


def discover_schema(db_name: str) -> dict:
    """Retrieve and parse a database's data source schema."""
    try:
        get_db_id(db_name)
    except ValueError:
        return None

    try:
        ds = retrieve_data_source_schema(db_name)
    except Exception as e:
        return {"error": str(e)}

    properties = {}
    for prop_name, prop_def in ds.get("properties", {}).items():
        prop_info = {"type": prop_def.get("type")}

        prop_type = prop_def.get("type")
        if prop_type == "select":
            options = prop_def.get("select", {}).get("options", [])
            prop_info["options"] = [o.get("name") for o in options]
        elif prop_type == "multi_select":
            options = prop_def.get("multi_select", {}).get("options", [])
            prop_info["options"] = [o.get("name") for o in options]
        elif prop_type == "status":
            options = prop_def.get("status", {}).get("options", [])
            prop_info["options"] = [o.get("name") for o in options]
        elif prop_type == "relation":
            rel = prop_def.get("relation", {})
            prop_info["related_db"] = rel.get("database_id")

        properties[prop_name] = prop_info

    return {
        "title": db_name,
        "ds_id": ds.get("id"),
        "properties": properties,
    }


def generate_markdown(schemas: dict) -> str:
    """Generate a markdown document from discovered schemas."""
    lines = [
        "# Notion Database Map",
        "",
        "Auto-generated by `tools/discover_schema.py`. Re-run to update.",
        "",
        "---",
        "",
    ]

    for db_name, schema in schemas.items():
        if schema is None:
            lines.append(f"## {db_name}")
            lines.append(f"*Not configured in .env*\n")
            continue

        if "error" in schema:
            lines.append(f"## {db_name}")
            lines.append(f"*Error: {schema['error']}*\n")
            continue

        lines.append(f"## {schema['title']}")
        lines.append(f"Data Source ID: `{schema['ds_id']}`\n")
        lines.append("| Property | Type | Options/Details |")
        lines.append("|----------|------|-----------------|")

        for prop_name, prop_info in sorted(schema["properties"].items()):
            details = ""
            if "options" in prop_info:
                details = ", ".join(prop_info["options"][:10])
                if len(prop_info.get("options", [])) > 10:
                    details += ", ..."
            elif "related_db" in prop_info:
                details = f"→ `{prop_info['related_db']}`"

            lines.append(f"| {prop_name} | {prop_info['type']} | {details} |")

        lines.append("")

    return "\n".join(lines)


def run(input_data: dict = None) -> dict:
    """Discover all database schemas and write the mapping file."""
    schemas = {}
    for db_name in DB_NAMES:
        print(f"  Discovering {db_name}...", end=" ", flush=True)
        schema = discover_schema(db_name)
        schemas[db_name] = schema
        if schema and "error" not in schema:
            prop_count = len(schema.get("properties", {}))
            print(f"OK ({prop_count} properties)")
        elif schema and "error" in schema:
            print(f"ERROR: {schema['error']}")
        else:
            print("SKIPPED (not in .env)")

    markdown = generate_markdown(schemas)

    output_path = os.path.join(os.path.dirname(__file__), "..", "workflows", "notion_database_map.md")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(markdown)

    print(f"\nSchema map written to workflows/notion_database_map.md")
    return {"status": "success", "databases_discovered": len(schemas)}


if __name__ == "__main__":
    run()
